FROM node:18-alpine AS builder
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies
COPY package.json .
COPY package-lock.json .
RUN npm install
# Bundle app source
COPY . .
# Build arguments
ARG NODE_VERSION=18-alpine
# Environment
ENV NODE_VERSION $NODE_VERSION
# Expose port
EXPOSE 3000

FROM postgres:15.0 AS postgres
ADD postgres/tables/ /docker-entrypoint-initdb.d/tables/
ADD postgres/seed/ /docker-entrypoint-initdb.d/seed/
ADD postgres/deploy_schemas.sql /docker-entrypoint-initdb.d/
# Copy built assets from builder
COPY --from=builder /usr/src/app /usr/src/app
# Expose port
EXPOSE 5432

FROM redis:2.8.9 AS redis
# Copy built assets from builder
COPY --from=builder /usr/src/app /usr/src/app
# Expose port
EXPOSE 6379
